/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author 182110041
 */
public class registroFuncionarioLogin extends javax.swing.JFrame {

    /**
     * Creates new form alunoMatricula
     */
    public registroFuncionarioLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtngSexoAlunoMatricula = new javax.swing.ButtonGroup();
        jpAlunoMatricula = new javax.swing.JPanel();
        jlblNomeAlunoMatricula = new javax.swing.JLabel();
        jlblNomeAlunoMatricula6 = new javax.swing.JLabel();
        jtfNomeAlunoMatricula = new javax.swing.JTextField();
        jlblNomeAlunoMatricula1 = new javax.swing.JLabel();
        jlblNomeAlunoMatricula2 = new javax.swing.JLabel();
        jbtnConfirmarAlunoMatricula = new javax.swing.JButton();
        jbtnConfirmarAlunoMatricula1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblNomeAlunoMatricula.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jlblNomeAlunoMatricula.setText("Usuário");

        jlblNomeAlunoMatricula6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N

        jtfNomeAlunoMatricula.setText("Entre 6 a 18 caracteres");
        jtfNomeAlunoMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNomeAlunoMatriculaFocusGained(evt);
            }
        });
        jtfNomeAlunoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeAlunoMatriculaActionPerformed(evt);
            }
        });

        jlblNomeAlunoMatricula1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jlblNomeAlunoMatricula1.setText("Senha");

        jlblNomeAlunoMatricula2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jlblNomeAlunoMatricula2.setText("Confirmar senha");

        jbtnConfirmarAlunoMatricula.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnConfirmarAlunoMatricula.setText("Confirmar");

        jbtnConfirmarAlunoMatricula1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnConfirmarAlunoMatricula1.setText("Cancelar");
        jbtnConfirmarAlunoMatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmarAlunoMatricula1ActionPerformed(evt);
            }
        });

        jPasswordField1.setToolTipText("Insira uma senha de no mínimo 6 caracteres contendo Maísculas, mínusculas, números e caracters especiais.");

        javax.swing.GroupLayout jpAlunoMatriculaLayout = new javax.swing.GroupLayout(jpAlunoMatricula);
        jpAlunoMatricula.setLayout(jpAlunoMatriculaLayout);
        jpAlunoMatriculaLayout.setHorizontalGroup(
            jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlunoMatriculaLayout.createSequentialGroup()
                .addGroup(jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAlunoMatriculaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jlblNomeAlunoMatricula6))
                    .addGroup(jpAlunoMatriculaLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jbtnConfirmarAlunoMatricula)
                        .addGap(55, 55, 55)
                        .addComponent(jbtnConfirmarAlunoMatricula1)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAlunoMatriculaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblNomeAlunoMatricula1)
                    .addComponent(jlblNomeAlunoMatricula)
                    .addComponent(jlblNomeAlunoMatricula2))
                .addGap(40, 40, 40)
                .addGroup(jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNomeAlunoMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jPasswordField1)
                    .addComponent(jPasswordField2))
                .addGap(27, 27, 27))
        );
        jpAlunoMatriculaLayout.setVerticalGroup(
            jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlunoMatriculaLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNomeAlunoMatricula)
                    .addComponent(jtfNomeAlunoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNomeAlunoMatricula1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNomeAlunoMatricula2)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jpAlunoMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConfirmarAlunoMatricula)
                    .addComponent(jbtnConfirmarAlunoMatricula1))
                .addGap(62, 62, 62)
                .addComponent(jlblNomeAlunoMatricula6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAlunoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAlunoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeAlunoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeAlunoMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeAlunoMatriculaActionPerformed

    private void jtfNomeAlunoMatriculaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeAlunoMatriculaFocusGained
        // TODO add your handling code here:
        jtfNomeAlunoMatricula.setText("");
    }//GEN-LAST:event_jtfNomeAlunoMatriculaFocusGained

    private void jbtnConfirmarAlunoMatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmarAlunoMatricula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConfirmarAlunoMatricula1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroFuncionarioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroFuncionarioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroFuncionarioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroFuncionarioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroFuncionarioLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JButton jbtnConfirmarAlunoMatricula;
    private javax.swing.JButton jbtnConfirmarAlunoMatricula1;
    private javax.swing.ButtonGroup jbtngSexoAlunoMatricula;
    private javax.swing.JLabel jlblNomeAlunoMatricula;
    private javax.swing.JLabel jlblNomeAlunoMatricula1;
    private javax.swing.JLabel jlblNomeAlunoMatricula2;
    private javax.swing.JLabel jlblNomeAlunoMatricula6;
    private javax.swing.JPanel jpAlunoMatricula;
    private javax.swing.JTextField jtfNomeAlunoMatricula;
    // End of variables declaration//GEN-END:variables
}
