/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Usuario;
import services.ServicosFactory;

/**
 *
 * @author 182110041
 */
public class telaLoginFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form alunoMatricula
     */
    public telaLoginFuncionario() {
        initComponents();

        jlblEsqueciSenha.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                System.out.println("clicado");
                //tenho que ver como voou fazer o frame
                JFrame frameRecuperaSenha = new JFrame("Recuperar senha");
                JPanel painelRecuperarSenha = new JPanel();
                JLabel jlblAvisoSairRecuperarSenha = new JLabel("Função ainda não implementada, favor fechar.");
                JButton jbtnSairRecuperarSenha = new JButton("OK");
                frameRecuperaSenha.setVisible(true);

                frameRecuperaSenha.setSize(400, 300);
                frameRecuperaSenha.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frameRecuperaSenha.setLayout(new FlowLayout(FlowLayout.CENTER, 30, 20));
                painelRecuperarSenha.add(jlblAvisoSairRecuperarSenha);
                painelRecuperarSenha.add(jbtnSairRecuperarSenha);
                //janela.add(painel);
                //janela.setVisible(true);
                //btnCadPessoa.addActionListener(this);
                //btnCadCarros.addActionListener(this);

                /*
        try (UsuarioServicos uServicos = ServicosFactory.getUsuarioServicos();) {
            Usuario u = uServicos.getByUsuario(jtfUsuario.getText());
            String senha = NLogin.geraSenha(String.valueOf(jpfSenha.getPassword()));
            if (senha.equals(u.getSenha())){
                Principal pForm = new Principal();
                pForm.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Usuário ou senha incorretos.", ".: Erro Login :.",JOptionPane.INFORMATION_MESSAGE );
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
                 */
            }
        });

    }

    public static String geraSenha(String senha) throws NoSuchAlgorithmException,
            UnsupportedEncodingException {
        MessageDigest mdMD5 = MessageDigest.getInstance("MD5");
        byte mdByteMD5[] = mdMD5.digest(senha.getBytes("UTF-8"));
        StringBuilder hexMDMD5 = new StringBuilder();
        for (byte b : mdByteMD5) {
            hexMDMD5.append(String.format("%02X", 0xFF & b));
        }
        String senhaMD5HashHex = hexMDMD5.toString();
        return senhaMD5HashHex;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtngSexoAlunoMatricula = new javax.swing.ButtonGroup();
        jpAlunoMatricula = new javax.swing.JPanel();
        jlblUsuarioTelaLogin = new javax.swing.JLabel();
        jlblNomeAlunoMatricula6 = new javax.swing.JLabel();
        jtfUsuarioTelaLogin = new javax.swing.JTextField();
        jlblSenhaTelaLogin = new javax.swing.JLabel();
        jbtnConfirmarTelaLogin = new javax.swing.JButton();
        jbtnCancelarTelaLogin = new javax.swing.JButton();
        jpfSenhaTelaLogin = new javax.swing.JPasswordField();
        jlblEsqueciSenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCHERHOM ACADEMIA - Login");

        jpAlunoMatricula.setBackground(new java.awt.Color(255, 255, 255));
        jpAlunoMatricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblUsuarioTelaLogin.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jlblUsuarioTelaLogin.setText("Usuário");
        jpAlunoMatricula.add(jlblUsuarioTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 59, -1));

        jlblNomeAlunoMatricula6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jpAlunoMatricula.add(jlblNomeAlunoMatricula6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 331, -1, -1));

        jtfUsuarioTelaLogin.setText("Entre 6 a 18 caracteres");
        jtfUsuarioTelaLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfUsuarioTelaLoginFocusGained(evt);
            }
        });
        jtfUsuarioTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioTelaLoginActionPerformed(evt);
            }
        });
        jpAlunoMatricula.add(jtfUsuarioTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 180, -1));

        jlblSenhaTelaLogin.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jlblSenhaTelaLogin.setText("Senha");
        jpAlunoMatricula.add(jlblSenhaTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 59, -1));

        jbtnConfirmarTelaLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnConfirmarTelaLogin.setText("Confirmar");
        jbtnConfirmarTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmarTelaLoginActionPerformed(evt);
            }
        });
        jpAlunoMatricula.add(jbtnConfirmarTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jbtnCancelarTelaLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnCancelarTelaLogin.setText("Cancelar");
        jbtnCancelarTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarTelaLoginActionPerformed(evt);
            }
        });
        jpAlunoMatricula.add(jbtnCancelarTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jpfSenhaTelaLogin.setToolTipText("Insira uma senha de no mínimo 6 caracteres contendo Maísculas, mínusculas, números e caracters especiais.");
        jpAlunoMatricula.add(jpfSenhaTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, -1));

        jlblEsqueciSenha.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jlblEsqueciSenha.setForeground(new java.awt.Color(0, 102, 255));
        jlblEsqueciSenha.setText("Esqueci minha senha");
        jpAlunoMatricula.add(jlblEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SCHERHOM ACADEMIA");
        jpAlunoMatricula.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 25)); // NOI18N
        jLabel2.setText("SCHERHOM ACADEMIA");
        jpAlunoMatricula.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpAlunoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAlunoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsuarioTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioTelaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioTelaLoginActionPerformed

    private void jtfUsuarioTelaLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfUsuarioTelaLoginFocusGained
        // TODO add your handling code here:
        jtfUsuarioTelaLogin.setText("");
    }//GEN-LAST:event_jtfUsuarioTelaLoginFocusGained

    private void jbtnCancelarTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarTelaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCancelarTelaLoginActionPerformed

    private void jbtnConfirmarTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmarTelaLoginActionPerformed
        // TODO add your handling code here:
        try ( UsuarioServicos uServicos = ServicosFactory.getUsuarioServicos();  Usuario u = uServicos.getByUsuario(jtfUsuarioTelaLogin);) {

            UsuarioServicos uServicos = ServicosFactory.getUsuarioServicos();
            Usuario u = uServicos.getByUsuario(jtfUsuario.getText());
            String senha = NLogin.geraSenha(String.valueOf(jpfSenha.getPassword()));
            if (senha.equals(u.getSenha())) {
                Principal pForm = new Principal();
                pForm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Usuário ou senha incorretos.", ".: Erro Login :.", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnConfirmarTelaLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLoginFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnCancelarTelaLogin;
    private javax.swing.JButton jbtnConfirmarTelaLogin;
    private javax.swing.ButtonGroup jbtngSexoAlunoMatricula;
    private javax.swing.JLabel jlblEsqueciSenha;
    private javax.swing.JLabel jlblNomeAlunoMatricula6;
    private javax.swing.JLabel jlblSenhaTelaLogin;
    private javax.swing.JLabel jlblUsuarioTelaLogin;
    private javax.swing.JPanel jpAlunoMatricula;
    private javax.swing.JPasswordField jpfSenhaTelaLogin;
    private javax.swing.JTextField jtfUsuarioTelaLogin;
    // End of variables declaration//GEN-END:variables
}
